name: Daily YouTube Upload - Trending Keywords

on:
  # 12:30 UTC = 18:00 IST
  schedule:
    # Weekdays at 7:00 AM, 1:00 PM, 5:00 PM and 8:00 PM IST
    - cron: '30 1,7,11,14 * * 1-5'
    # Weekends at 8:00 AM, 1:00 PM, 5:00 PM and 8:00 PM IST
    - cron: '30 2,7,11,14 * * 6,0'
  workflow_dispatch:  # Allow manual runs too

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

#      - name: Install Hindi (Devanagari) fonts
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji fonts-noto-unhinted

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Export secret to .env file
        run: echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" > .env

      - name: Restore token.pkl
        run: |
          echo "${{ secrets.TOKEN_PKL_B64 }}" | base64 -d > token.pkl

      - name: Write client_secrets.json
        run: |
          echo "${{ secrets.CLIENT_SECRETS_B64 }}" | base64 -d > client_secrets.json

      - name: Cache trending hashtags history
        uses: actions/cache@v3
        with:
          path: output/history/trending_hashtags.txt
          key: trending-hashtags-latest
          restore-keys: |
            trending-hashtags-

      - name: Check cached file presence
        run: |
          if [ -f output/history/trending_hashtags.txt ]; then
            echo "âœ… Trending hashtags file found in cache."
            cat output/history/trending_hashtags.txt
          else
            echo "âŒ No cached trending hashtags file found."
          fi

      - name: Run upload script
        run: python main.py keywords

      - name: Show updated trending hashtags file
        run: |
          echo "ğŸ”„ Updated trending hashtags:"
          cat output/history/trending_hashtags.txt
